AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AmplifyRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: amplifyconsole-video-assessment-backend-role
      Description: IAM Role to deploy amplify Video Assessment Project
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify
      Policies:
        - PolicyName: video-assessment-extended-policy
          PolicyDocument: # JSON policy document
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:*
                  - ssm:AddTagsToResource
                  - iam:ListPolicies
                  - iam:CreatePolicies
                  - iam:ReadPolicies
                  - iam:ListRoles
                  - iam:AttachRolePolicy
                Resource: "*"
